"""CLI tool for jokester-p agent."""

from __future__ import annotations

import argparse
from typing import TYPE_CHECKING, Any

from appinfra.app.tools import Tool, ToolConfig
from appinfra.db.pg import PG
from llm_learn import IsolationContext, LearnClient
from llm_learn.core import Database
from sqlalchemy import text

from .pairing import PairingService
from .rating import RatingService


if TYPE_CHECKING:
    from ...core.llm import LLMCaller


class JokesterCLI(Tool):
    """CLI commands for jokester-p agent.

    Provides agent-specific commands:
    - stats: Show joke rating statistics
    - rate: Rate unrated jokes in batches
    - train: Create preference pairs and training run for DPO
    """

    def __init__(self, parent: Any = None) -> None:
        config = ToolConfig(name="jokester-p", help_text="Jokester agent CLI commands")
        super().__init__(parent, config)
        self._pg: PG | None = None

    def configure(self) -> None:
        """Set up database connection."""
        if not hasattr(self.app, "config"):
            raise RuntimeError("App does not have config")

        db_config = self.app.config.learn.db
        if db_config is None:
            raise RuntimeError("Database configuration not found in learn.db")

        self._pg = PG(self.lg, db_config)

    def add_args(self, parser: argparse.ArgumentParser) -> None:
        subparsers = parser.add_subparsers(dest="command", help="Command to run")
        self._add_stats_args(subparsers)
        self._add_rate_args(subparsers)
        self._add_train_args(subparsers)

    def _add_stats_args(self, subparsers: Any) -> None:
        """Add stats command arguments."""
        p = subparsers.add_parser("stats", help="Show joke rating statistics")
        p.add_argument(
            "--max-chars",
            type=int,
            default=140,
            help="Only count jokes under this character length (default: 140)",
        )

    def _add_rate_args(self, subparsers: Any) -> None:
        """Add rate command arguments."""
        p = subparsers.add_parser("rate", help="Rate unrated jokes in batches")
        p.add_argument("--limit", type=int, help="Maximum jokes to rate (default: all unrated)")
        p.add_argument(
            "--batch-size", type=int, help="Jokes per API call (default: from config, typically 5)"
        )
        p.add_argument(
            "--dry-run", action="store_true", help="Show what would be rated without sending to LLM"
        )

    def _add_train_args(self, subparsers: Any) -> None:
        """Add train command with dpo/sft subcommands."""
        train_parser = subparsers.add_parser("train", help="Training commands (DPO/SFT)")
        train_parser.add_argument(
            "--based-on",
            "-b",
            type=int,
            dest="based_on",
            help="Train on top of existing run ID (for lineage)",
        )
        train_subs = train_parser.add_subparsers(dest="train_command", help="Training type")
        self._add_train_dpo_args(train_subs)
        self._add_train_sft_args(train_subs)

    def _add_train_dpo_args(self, subparsers: Any) -> None:
        """Add DPO training arguments."""
        p = subparsers.add_parser("dpo", help="Create preference pairs for DPO training")
        p.add_argument(
            "--adapter-name",
            type=str,
            default="jokester-dpo",
            help="Name for the trained adapter (default: jokester-dpo)",
        )
        p.add_argument(
            "--dry-run", action="store_true", help="Show what would be created without saving"
        )
        self._add_pairing_args(p)

    def _add_train_sft_args(self, subparsers: Any) -> None:
        """Add SFT training arguments."""
        p = subparsers.add_parser("sft", help="Train on high-rated jokes (SFT)")
        p.add_argument(
            "--adapter-name",
            type=str,
            default="jokester-sft",
            help="Name for the trained adapter (default: jokester-sft)",
        )
        p.add_argument(
            "--min-stars",
            type=int,
            default=4,
            help="Minimum star rating for inclusion (default: 4)",
        )
        p.add_argument(
            "--max-chars",
            type=int,
            default=140,
            help="Only include jokes under this character length (default: 140)",
        )
        p.add_argument(
            "--model", type=str, help="Only include jokes generated by this model (substring match)"
        )
        p.add_argument("--max", type=int, dest="max_examples", help="Maximum examples to include")
        p.add_argument(
            "--dry-run", action="store_true", help="Show what would be created without saving"
        )

    def _add_pairing_args(self, p: Any) -> None:
        """Add pairing-related arguments to a parser."""
        p.add_argument(
            "--margin",
            type=int,
            default=None,
            help="Minimum star difference for pairing (default: from config, typically 3)",
        )
        p.add_argument(
            "--min",
            type=int,
            dest="min_pairs",
            help="Minimum pairs to generate (reuses chosen jokes with multiple rejected if needed)",
        )
        p.add_argument(
            "--max", type=int, dest="max_pairs", help="Maximum pairs to include (default: all)"
        )
        p.add_argument(
            "--max-chars",
            type=int,
            default=140,
            help="Only include jokes under this character length (default: 140)",
        )
        p.add_argument(
            "--no-reuse", action="store_true", help="Each chosen joke used at most once (1:1)"
        )
        p.add_argument(
            "--model", type=str, help="Only include jokes generated by this model (substring match)"
        )

    def run(self, **kwargs: Any) -> int:
        command = self.args.command

        if command == "stats":
            return self._cmd_stats()
        elif command == "rate":
            return self._cmd_rate()
        elif command == "train":
            train_cmd = getattr(self.args, "train_command", None)
            if train_cmd == "dpo":
                return self._cmd_train_dpo()
            elif train_cmd == "sft":
                return self._cmd_train_sft()
            else:
                print("Usage: agent jokester-p train <dpo|sft>")
                return 1
        else:
            print("Usage: agent jokester-p <command>")
            print("Commands: stats, rate, train")
            return 1

    def _cmd_stats(self) -> int:
        """Show joke rating statistics."""
        assert self._pg is not None

        max_chars = getattr(self.args, "max_chars", 130)
        stats = self._get_rating_stats(exclude_haiku=True, max_chars=max_chars)
        dist = self._get_rating_distribution(exclude_haiku=True, max_chars=max_chars)

        self._print_stats_header(max_chars)
        self._print_rating_summary(stats, dist)
        self._print_training_run_stats(max_chars=max_chars)
        self._print_haiku_stats(max_chars=max_chars)

        return 0

    def _print_stats_header(self, max_chars: int) -> None:
        """Print stats header with model and adapter info."""
        context_key = self._get_context_key()
        model = self._get_latest_model(context_key) or "unknown"
        adapter = self._get_latest_adapter(context_key)
        print("\n=== Jokester-p Stats ===\n")
        print(f"Model:   {model}, <{max_chars} chars")
        if adapter:
            print(f"Adapter: {adapter['name']} (md5: {adapter['md5']}, mtime: {adapter['mtime']})")
        print()

    def _print_rating_summary(self, stats: dict[str, Any], dist: list[dict[str, Any]]) -> None:
        """Print rating counts and distribution."""
        print(f"Total jokes:  {stats['total']}")
        print(f"Rated:        {stats['rated']}")
        print(f"Unrated:      {stats['unrated']}")
        avg = f"{stats['avg_stars']:.2f}" if stats["avg_stars"] else "N/A"
        print(f"Avg stars:    {avg}")
        print()
        print("Rating Distribution:")
        for row in dist:
            stars_visual = "★" * row["stars"] + "☆" * (5 - row["stars"])
            print(f"  {stars_visual}  {row['count']:4d}  ({row['pct']:.1f}%)")

    def _print_training_run_stats(self, max_chars: int | None = None) -> None:
        """Print stats broken down by training runs."""
        runs = self._get_training_runs()
        if not runs:
            return

        print("\n=== By Training Run ===\n")
        period_stats = self._get_stats_by_training_period(runs, max_chars=max_chars)

        for period in period_stats:
            if period["count"] == 0:
                continue
            avg = f"{period['avg_stars']:.2f}" if period["avg_stars"] else "N/A"
            dist = period.get("distribution", {})
            total = period["count"]
            stars_str = self._format_star_distribution(dist, total)
            print(f"{period['period']:20s}  {period['count']:5d} jokes  avg={avg}  {stars_str}")
        print()

    def _format_star_distribution(self, dist: dict[int, int], total: int) -> str:
        """Format star distribution as: 5★:0(0.0%)  4★:18(0.2%)  3★:504(6.3%)  ..."""
        parts = []
        for stars in (5, 4, 3, 2, 1):
            count = dist.get(stars, 0)
            pct = count * 100 / total if total else 0
            parts.append(f"{stars}★:{count}({pct:.1f}%)")
        return "  ".join(parts)

    def _print_haiku_stats(self, max_chars: int | None = None) -> None:
        """Print stats for Haiku-generated jokes separately."""
        assert self._pg is not None

        stats = self._query_haiku_stats(max_chars)
        if stats["total"] == 0:
            return

        chars_label = f", <{max_chars} chars" if max_chars else ""
        print(f"=== Haiku (Reference{chars_label}) ===\n")
        avg_str = f"{float(stats['avg_stars']):.2f}" if stats["avg_stars"] else "N/A"
        stars_str = self._format_star_distribution(stats["dist"], stats["rated"])
        print(f"{'haiku':20s}  {stats['total']:5d} jokes  avg={avg_str}  {stars_str}")
        print()

    def _get_latest_adapter(self, context_key: str) -> dict[str, Any] | None:
        """Get latest adapter info from completed DPO run."""
        assert self._pg is not None
        sql = text("""
            SELECT id, adapter->>'name' as adapter_name,
                   adapter->>'md5' as md5, adapter->>'mtime' as mtime, completed_at
            FROM training_runs
            WHERE context_key = :context_key AND status = 'completed'
            ORDER BY completed_at DESC
            LIMIT 1
        """)
        with self._pg.connect() as conn:
            row = conn.execute(sql, {"context_key": context_key}).fetchone()
        if row is None:
            return None
        return {
            "run_id": row[0],
            "name": row[1],
            "md5": row[2],
            "mtime": row[3],
            "completed_at": row[4].strftime("%Y-%m-%d %H:%M") if row[4] else "N/A",
        }

    def _get_latest_model(self, context_key: str) -> str | None:
        """Get base model name from most recent joke."""
        assert self._pg is not None
        sql = text("""
            SELECT t.base_model
            FROM agent_jokester_training t
            JOIN atomic_facts af ON t.fact_id = af.id
            WHERE af.context_key = :context_key
            ORDER BY af.id DESC
            LIMIT 1
        """)
        with self._pg.connect() as conn:
            row = conn.execute(sql, {"context_key": context_key}).fetchone()
        return row[0] if row else None

    def _query_haiku_stats(self, max_chars: int | None = None) -> dict[str, Any]:
        """Query stats for Haiku-generated jokes."""
        assert self._pg is not None
        context_key = self._get_context_key()
        chars_join, chars_filter = self._build_chars_filter(max_chars)

        sql = text(f"""
            SELECT COUNT(*) as total, COUNT(afd.id) as rated,
                   AVG((afd.context->>'stars')::int) as avg_stars
            FROM atomic_facts af
            JOIN agent_jokester_model_usage u ON u.fact_id = af.id
            {chars_join}
            LEFT JOIN atomic_feedback_details afd ON af.id = afd.fact_id
            WHERE af.context_key = :context_key AND af.type = 'solution'
              AND u.model_name LIKE '%haiku%' {chars_filter}
        """)
        with self._pg.connect() as conn:
            row = conn.execute(sql, {"context_key": context_key}).fetchone()
            total, rated, avg_stars = row[0], row[1], row[2]
            dist = self._query_haiku_distribution(conn, context_key, chars_join, chars_filter)

        return {"total": total, "rated": rated, "avg_stars": avg_stars, "dist": dist}

    def _query_haiku_distribution(
        self, conn: Any, context_key: str, chars_join: str, chars_filter: str
    ) -> dict[int, int]:
        """Query star distribution for Haiku jokes."""
        sql = text(f"""
            SELECT (afd.context->>'stars')::int as stars, COUNT(*) as cnt
            FROM atomic_facts af
            JOIN agent_jokester_model_usage u ON u.fact_id = af.id
            {chars_join}
            JOIN atomic_feedback_details afd ON af.id = afd.fact_id
            WHERE af.context_key = :context_key AND af.type = 'solution'
              AND u.model_name LIKE '%haiku%' {chars_filter}
            GROUP BY (afd.context->>'stars')::int
        """)
        rows = conn.execute(sql, {"context_key": context_key}).fetchall()
        return {r[0]: r[1] for r in rows}

    def _build_chars_filter(self, max_chars: int | None) -> tuple[str, str]:
        """Build JOIN and WHERE clause for character length filtering."""
        if not max_chars:
            return "", ""
        chars_join = "JOIN atomic_solution_details asd ON asd.fact_id = af.id"
        chars_filter = f"AND length(asd.answer_text) < {max_chars}"
        return chars_join, chars_filter

    def _cmd_rate(self) -> int:
        """Rate unrated jokes in batches."""
        assert self._pg is not None

        rate_config = self._load_rate_config()
        if rate_config is None:
            return 1

        prompt_template, batch_size, provider, model = rate_config
        dry_run = getattr(self.args, "dry_run", False)

        llm_caller = self._create_llm_caller(dry_run=dry_run)
        if llm_caller is None:
            print("Error: Could not create LLM caller")
            return 1

        try:
            service = RatingService(
                lg=self.lg,
                pg=self._pg,
                llm_caller=llm_caller,
                prompt_template=prompt_template,
                context_key=self._get_context_key(),
                batch_size=batch_size,
                provider=provider,
                model=model,
            )
            return self._run_rating(service, batch_size)
        finally:
            llm_caller.close()

    def _load_rate_config(self) -> tuple[str, int, str, str] | None:
        """Load rating config. Returns (prompt, batch_size, provider, model) or None."""
        agent_config = self._get_agent_config()
        if agent_config is None:
            print("Error: Could not load agent config")
            return None

        rating_config = agent_config.get("rating", {})
        prompt_template = self._get_prompt_template(rating_config)
        config_batch_size = rating_config.get("batch_size", 5)
        batch_size = self.args.batch_size or config_batch_size

        # Extract provider and model from first enabled provider
        provider, model = self._get_provider_settings(rating_config)

        return (prompt_template, batch_size, provider, model)

    def _run_rating(self, service: RatingService, batch_size: int) -> int:
        """Execute rating and print results."""
        unrated = service.get_unrated_jokes(self.args.limit)
        if not unrated:
            print("No unrated jokes found.")
            return 0

        print(f"\nUnrated jokes: {len(unrated)}")
        print(f"Batch size: {batch_size}")
        print(f"Estimated batches: {(len(unrated) + batch_size - 1) // batch_size}")
        print()

        total_rated = 0
        batch_count = 0

        for batch in service.rate_batches(limit=self.args.limit, batch_size=batch_size):
            batch_count += 1
            for r in batch:
                total_rated += 1
                stars = "★" * r.stars + "☆" * (5 - r.stars)
                joke = r.content[:90] + "..." if len(r.content) > 90 else r.content
                print(f"{r.id}  ({r.stars})  {stars}  {joke}")

        print(f"\n✓ Rated: {total_rated}")
        print(f"  Batches: {batch_count}")

        return 0

    def _cmd_train_dpo(self) -> int:
        """Create preference pairs from rated jokes and set up DPO training run."""
        assert self._pg is not None
        opts = self._get_train_options()

        result = self._get_preference_pairs(
            opts["margin"],
            opts["min_pairs"],
            opts["max_pairs"],
            opts["max_chars"],
            opts["no_reuse"],
            opts["model"],
        )

        if not result.pairs:
            print("\nNo preference pairs available for training.")
            return 0

        return self._finalize_training(result, opts)

    def _finalize_training(self, result: Any, opts: dict[str, Any]) -> int:
        """Print summary and execute training run."""
        self._print_train_summary(
            len(result.pairs),
            opts["adapter_name"],
            opts["margin"],
            opts["dry_run"],
            opts.get("based_on"),
        )
        self._print_pairs_sample(result.pairs)
        self._print_model_contribution(result.pairs)

        if opts["dry_run"]:
            print("Dry run complete. Use without --dry-run to create training run.")
            return 0

        client = self._create_training_client()
        self._execute_training_run(
            client, result.pairs, opts["adapter_name"], based_on=opts.get("based_on")
        )
        return 0

    def _cmd_train_sft(self) -> int:
        """Train on high-rated jokes using SFT."""
        assert self._pg is not None
        opts = self._get_sft_options()

        examples = self._get_sft_examples(opts)
        if not examples:
            print("\nNo examples available for SFT training.")
            return 0

        self._print_sft_summary(examples, opts)

        if opts["dry_run"]:
            print("Dry run complete. Use without --dry-run to create training run.")
            return 0

        client = self._create_training_client()
        self._execute_sft_run(client, examples, opts["adapter_name"])
        return 0

    def _get_sft_options(self) -> dict[str, Any]:
        """Extract SFT command options from args."""
        return {
            "adapter_name": getattr(self.args, "adapter_name", "jokester-sft"),
            "min_stars": getattr(self.args, "min_stars", 4),
            "max_chars": getattr(self.args, "max_chars", 130),
            "model": getattr(self.args, "model", None),
            "max_examples": getattr(self.args, "max_examples", None),
            "dry_run": getattr(self.args, "dry_run", False),
        }

    def _get_sft_examples(self, opts: dict[str, Any]) -> list[Any]:
        """Get high-rated jokes for SFT training."""
        assert self._pg is not None
        service = PairingService(self.lg, self._pg, self._get_context_key())
        all_jokes = service.get_rated_jokes(max_chars=opts["max_chars"], model=opts["model"])

        # Filter by minimum stars
        filtered = [j for j in all_jokes if j.stars >= opts["min_stars"]]

        # Apply max cap
        if opts["max_examples"] is not None and len(filtered) > opts["max_examples"]:
            filtered = filtered[: opts["max_examples"]]

        return filtered

    def _print_sft_summary(self, examples: list[Any], opts: dict[str, Any]) -> None:
        """Print SFT training summary."""
        print("\n=== SFT Training ===")
        print(f"Min stars:      {opts['min_stars']}")
        print(f"Max chars:      {opts['max_chars']}")
        if opts["model"]:
            print(f"Model filter:   {opts['model']}")
        if opts["max_examples"]:
            print(f"Max examples:   {opts['max_examples']}")
        print(f"Examples:       {len(examples)}")
        print()

        # Print sample
        print("Sample examples:")
        for i, ex in enumerate(examples[:5], 1):
            stars_visual = "★" * ex.stars + "☆" * (5 - ex.stars)
            content = ex.content[:50] + "..." if len(ex.content) > 50 else ex.content
            print(f"  {i}. {stars_visual}  {content}")
        if len(examples) > 5:
            print(f"  ... and {len(examples) - 5} more")
        print()

        # Print model contribution
        fact_ids = {ex.id for ex in examples}
        self._print_model_contribution_for_facts(fact_ids)

        # Print adapter info
        print(f"Adapter:        {opts['adapter_name']}")
        if opts["dry_run"]:
            print("(Dry run - training run not created)")

    def _execute_sft_run(self, client: LearnClient, examples: list[Any], adapter_name: str) -> None:
        """Create SFT run and assign examples, printing results."""
        self.lg.debug("creating SFT training run...", extra={"adapter_name": adapter_name})
        run_info = client.train.sft.create(
            adapter_name=adapter_name,
            on_replace=self._confirm_replace_run,
        )
        self.lg.debug("created SFT training run", extra={"run_id": run_info.id})

        # Assign examples (just fact IDs for SFT)
        fact_ids = [ex.id for ex in examples]
        self.lg.debug(
            "assigning examples to SFT run...",
            extra={"run_id": run_info.id, "count": len(examples)},
        )
        assigned = client.train.sft.assign_examples(run_info.id, fact_ids)
        self.lg.debug("assigned examples", extra={"assigned": assigned})

        print(f"\n✓ Created SFT training run #{run_info.id}")
        print(f"  Adapter: {adapter_name}")
        print(f"  Examples assigned: {assigned}")
        print(f"  Status: {run_info.status}")

    def _get_train_options(self) -> dict[str, Any]:
        """Extract train command options from args."""
        config_margin = self._get_pairing_config().get("margin", 2)
        return {
            "margin": getattr(self.args, "margin", None) or config_margin,
            "dry_run": getattr(self.args, "dry_run", False),
            "min_pairs": getattr(self.args, "min_pairs", None),
            "max_pairs": getattr(self.args, "max_pairs", None),
            "max_chars": getattr(self.args, "max_chars", 130),
            "no_reuse": getattr(self.args, "no_reuse", False),
            "adapter_name": getattr(self.args, "adapter_name", "jokester-dpo"),
            "model": getattr(self.args, "model", None),
            "based_on": getattr(self.args, "based_on", None),
        }

    def _get_preference_pairs(
        self,
        margin: int,
        min_pairs: int | None,
        max_pairs: int | None,
        max_chars: int | None = None,
        no_reuse: bool = False,
        model: str | None = None,
    ) -> Any:
        """Get preference pairs from rated jokes. Returns PairingResult (in-memory)."""
        assert self._pg is not None
        service = PairingService(self.lg, self._pg, self._get_context_key())
        result = service.create_pairs(
            strategy="relative",
            margin=margin,
            min_pairs=min_pairs,
            max_pairs=max_pairs,
            max_chars=max_chars,
            no_reuse=no_reuse,
            model=model,
        )
        self._print_pairing_summary(
            result, margin, min_pairs, max_pairs, max_chars, no_reuse, model
        )
        return result

    def _print_pairing_summary(
        self,
        result: Any,
        margin: int,
        min_pairs: int | None,
        max_pairs: int | None,
        max_chars: int | None,
        no_reuse: bool = False,
        model: str | None = None,
    ) -> None:
        """Print pairing operation summary."""
        print("\n=== Pairing ===")
        print(f"Rated jokes:    {result.total_rated}")
        print(f"Max chars:      {max_chars or 'unlimited'}")
        print(f"Margin:         {margin} stars")
        if model:
            print(f"Model filter:   {model}")
        if min_pairs is not None:
            print(f"Min pairs:      {min_pairs}")
        if max_pairs is not None:
            print(f"Max pairs:      {max_pairs}")
        if no_reuse:
            print("No reuse:       yes (1:1 pairing)")
        print(f"New pairs:      {len(result.pairs)}")

    def _create_training_client(self) -> LearnClient:
        """Create LearnClient for agent's context."""
        assert self._pg is not None
        db = Database(self.lg, self._pg)
        context = IsolationContext(context_key=self._get_context_key())
        return LearnClient(lg=self.lg, database=db, context=context)

    def _get_context_key(self) -> str:
        """Get context_key from agent identity config."""
        from llm_agent.core.agent import Identity

        agent_config = self._get_agent_config()
        if agent_config is None:
            raise RuntimeError("Could not load agent config")
        identity_config = agent_config.get("identity", {})
        identity = Identity.from_config(identity_config)
        return identity.context_key

    def _execute_training_run(
        self,
        client: LearnClient,
        pairs: list[Any],
        adapter_name: str,
        based_on: int | None = None,
    ) -> None:
        """Create run and assign pairs, printing results."""
        self.lg.debug("creating training run...", extra={"adapter_name": adapter_name})
        run_info = client.train.dpo.create(
            adapter_name=adapter_name,
            based_on=based_on,
            on_replace=self._confirm_replace_run,
        )
        self.lg.debug("created training run", extra={"run_id": run_info.id})

        # Create PairTuples: (chosen_fact_id, rejected_fact_id, prompt)
        pair_tuples = [(p.chosen.id, p.rejected.id, "Tell me a joke.") for p in pairs]
        self.lg.debug(
            "assigning pairs to run...", extra={"run_id": run_info.id, "count": len(pairs)}
        )
        assigned = client.train.dpo.assign_pairs(run_info.id, pair_tuples)
        self.lg.debug("assigned pairs", extra={"assigned": assigned})

        print(f"\n✓ Created training run #{run_info.id}")
        print(f"  Adapter: {adapter_name}")
        print(f"  Pairs assigned: {assigned}")
        print(f"  Status: {run_info.status}")

    def _confirm_replace_run(self, existing: Any) -> bool:
        """Ask user to confirm replacing an existing pending run."""
        print(f"\nFound existing pending run #{existing.id} (adapter: {existing.adapter_name})")
        response = input("Replace it? [Y/n] ").strip().lower()
        return response != "n"

    def _print_train_summary(
        self,
        total_pairs: int,
        adapter_name: str,
        margin: int,
        dry_run: bool,
        based_on: int | None = None,
    ) -> None:
        """Print training run summary."""
        print("\n=== Training Run ===")
        print(f"Adapter:        {adapter_name}")
        if based_on:
            print(f"Based on:       run #{based_on}")
        print(f"Margin:         {margin} stars")
        print(f"Total pairs:    {total_pairs}")
        if dry_run:
            print("(Dry run - training run not created)")
        print()

    def _print_pairs_sample(self, pairs: list[Any], max_show: int = 5) -> None:
        """Print sample of pairs to be included."""
        print("Sample pairs:")
        for i, pair in enumerate(pairs[:max_show], 1):
            chosen = (
                pair.chosen.content[:50] + "..."
                if len(pair.chosen.content) > 50
                else pair.chosen.content
            )
            rejected = (
                pair.rejected.content[:50] + "..."
                if len(pair.rejected.content) > 50
                else pair.rejected.content
            )
            print(f"  {i}. margin={pair.margin}")
            print(f"     chosen:   {chosen}")
            print(f"     rejected: {rejected}")
        if len(pairs) > max_show:
            print(f"  ... and {len(pairs) - max_show} more")
        print()

    def _print_model_contribution(self, pairs: list[Any]) -> None:
        """Print breakdown of which models contributed jokes to the pairs."""
        fact_ids = {fid for p in pairs for fid in (p.chosen.id, p.rejected.id)}
        self._print_model_contribution_for_facts(fact_ids)

    def _print_model_contribution_for_facts(self, fact_ids: set[int]) -> None:
        """Print breakdown of which models contributed to the given facts."""
        if not fact_ids:
            return

        rows = self._query_model_usage(fact_ids)
        if not rows:
            return

        print("Model contribution:")
        total = sum(r[1] for r in rows)
        for model_name, count in rows:
            pct = count * 100 / total
            short_name = model_name.split("/")[-1] if "/" in model_name else model_name
            print(f"  {short_name:40s} {count:5d} ({pct:5.1f}%)")
        print()

    def _query_model_usage(self, fact_ids: set[int]) -> list[Any]:
        """Query model usage counts for given fact IDs."""
        assert self._pg is not None
        self.lg.debug("querying model contribution...", extra={"fact_count": len(fact_ids)})
        sql = text("""
            SELECT model_name, COUNT(*) as cnt
            FROM agent_jokester_model_usage
            WHERE fact_id = ANY(:fact_ids)
            GROUP BY model_name
            ORDER BY cnt DESC
        """)
        with self._pg.connect() as conn:
            rows: list[Any] = conn.execute(sql, {"fact_ids": list(fact_ids)}).fetchall()
            return rows

    def _get_agent_config(self) -> dict[str, Any] | None:
        """Get jokester-p agent config."""
        if not hasattr(self.app, "config") or not hasattr(self.app.config, "agents"):
            return None
        config = self.app.config.agents.get("jokester-p")
        return dict(config) if config else None

    def _get_pairing_config(self) -> dict[str, Any]:
        """Get pairing config from agent config."""
        agent_config = self._get_agent_config()
        if agent_config is None:
            return {}
        rating_config = agent_config.get("rating", {})
        return dict(rating_config.get("pairing", {}))

    def _get_prompt_template(self, rating_config: dict[str, Any]) -> str:
        """Extract prompt template from rating config."""
        models = rating_config.get("models", {})
        atomic = models.get("atomic", {})
        solution = atomic.get("solution", {})
        return str(solution.get("prompt", "Rate this content 1-5 stars."))

    def _get_provider_settings(self, rating_config: dict[str, Any]) -> tuple[str, str]:
        """Extract provider name and model from first enabled provider.

        Returns:
            Tuple of (provider, model). Provider is used for both routing and identification.
        """
        providers = rating_config.get("providers", {})
        for name, config in providers.items():
            if not config.get("enabled", True):
                continue
            backend_config = config.get("backend", {})
            model = backend_config.get("model", "auto")
            return (name, model)
        return ("local", "auto")

    def _create_llm_caller(self, dry_run: bool = False) -> LLMCaller | None:
        """Create LLM caller from config.

        Args:
            dry_run: If True, caller will log but not send requests.
        """
        from llm_infer.client import Factory as LLMClientFactory

        from ...core.llm import LLMCaller

        llm_config = self.app.config.get("llm", {})
        try:
            router = LLMClientFactory(self.lg).from_config(llm_config)
            return LLMCaller(self.lg, router, dry_run=dry_run)
        except Exception as e:
            self.lg.error("failed to create LLM caller", extra={"exception": e})
            return None

    def _get_rating_stats(
        self, exclude_haiku: bool = False, max_chars: int | None = None
    ) -> dict[str, Any]:
        """Get rating statistics using lateral subquery for latest feedback per fact."""
        assert self._pg is not None
        context_key = self._get_context_key()
        haiku_filter = self._build_haiku_filter(exclude_haiku)
        chars_join, chars_filter = self._build_chars_filter(max_chars)

        sql = text(f"""
            SELECT COUNT(*) as total,
                   COUNT(*) FILTER (WHERE afd.id IS NOT NULL) as rated,
                   COUNT(*) FILTER (WHERE afd.id IS NULL) as unrated,
                   AVG((afd.context->>'stars')::int) as avg_stars
            FROM atomic_facts af
            {chars_join}
            LEFT JOIN LATERAL (
                SELECT afd2.id, afd2.context FROM atomic_feedback_details afd2
                WHERE afd2.fact_id = af.id ORDER BY afd2.id DESC LIMIT 1
            ) afd ON true
            WHERE af.context_key = :context_key AND af.type = 'solution'
              {haiku_filter} {chars_filter}
        """)
        with self._pg.connect() as conn:
            result = conn.execute(sql, {"context_key": context_key}).fetchone()
        return {
            "total": result[0],
            "rated": result[1],
            "unrated": result[2],
            "avg_stars": float(result[3]) if result[3] else None,
        }

    def _build_haiku_filter(self, exclude_haiku: bool) -> str:
        """Build WHERE clause to exclude Haiku jokes."""
        if not exclude_haiku:
            return ""
        return """AND NOT EXISTS (
            SELECT 1 FROM agent_jokester_model_usage u
            WHERE u.fact_id = af.id AND u.model_name LIKE '%haiku%'
        )"""

    def _get_rating_distribution(
        self, exclude_haiku: bool = False, max_chars: int | None = None
    ) -> list[dict[str, Any]]:
        """Get rating distribution using DISTINCT ON for latest rating per fact."""
        assert self._pg is not None
        context_key = self._get_context_key()
        haiku_filter = self._build_haiku_filter(exclude_haiku)
        chars_join, chars_filter = self._build_chars_filter(max_chars)

        sql = text(f"""
            WITH latest_ratings AS (
                SELECT DISTINCT ON (af.id) (afd.context->>'stars')::int as stars
                FROM atomic_facts af
                JOIN atomic_feedback_details afd ON af.id = afd.fact_id
                {chars_join}
                WHERE af.context_key = :context_key AND af.type = 'solution'
                  {haiku_filter} {chars_filter}
                ORDER BY af.id, afd.id DESC
            )
            SELECT stars, COUNT(*) as count,
                   ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 1) as pct
            FROM latest_ratings GROUP BY stars ORDER BY stars DESC
        """)
        with self._pg.connect() as conn:
            rows = conn.execute(sql, {"context_key": context_key}).fetchall()
        return [{"stars": r[0], "count": r[1], "pct": float(r[2])} for r in rows]

    def _get_training_runs(self) -> list[dict[str, Any]]:
        """Get completed training runs ordered by completion time."""
        assert self._pg is not None
        context_key = self._get_context_key()
        sql = text("""
            SELECT id, adapter->>'name' as adapter_name, completed_at
            FROM training_runs
            WHERE context_key = :context_key AND status = 'completed'
            ORDER BY completed_at
        """)
        with self._pg.connect() as conn:
            rows = conn.execute(sql, {"context_key": context_key}).fetchall()
        return [{"id": r[0], "adapter_name": r[1], "completed_at": r[2]} for r in rows]

    def _get_stats_by_training_period(
        self, runs: list[dict[str, Any]], max_chars: int | None = None
    ) -> list[dict[str, Any]]:
        """Get rating stats for each training period."""
        assert self._pg is not None
        context_key = self._get_context_key()
        periods = []

        # Build time boundaries: [None, run1_completed, run2_completed, ...]
        boundaries = [None] + [r["completed_at"] for r in runs] + [None]

        for i in range(len(boundaries) - 1):
            start = boundaries[i]
            end = boundaries[i + 1]

            period_name = "pre-training" if i == 0 else f"after run #{runs[i - 1]['id']}"

            stats = self._get_period_stats(context_key, start, end, max_chars=max_chars)
            stats["period"] = period_name
            periods.append(stats)

        return periods

    def _get_period_stats(
        self, context_key: str, start: Any, end: Any, max_chars: int | None = None
    ) -> dict[str, Any]:
        """Get stats for jokes created between start and end times."""
        assert self._pg is not None

        where, params, extra_join = self._build_period_conditions(
            context_key, start, end, max_chars=max_chars
        )
        sql = text(f"""
            SELECT COUNT(*) as count, AVG((afd.context->>'stars')::int) as avg_stars
            FROM atomic_facts af
            JOIN atomic_feedback_details afd ON af.id = afd.fact_id
            {extra_join}
            WHERE {where}
        """)

        with self._pg.connect() as conn:
            row = conn.execute(sql, params).fetchone()
            count, avg_stars = row[0], float(row[1]) if row[1] else None
            distribution = self._get_star_distribution(conn, where, params, extra_join)

        return {"count": count, "avg_stars": avg_stars, "distribution": distribution}

    def _build_period_conditions(
        self, context_key: str, start: Any, end: Any, max_chars: int | None = None
    ) -> tuple[str, dict[str, Any], str]:
        """Build WHERE conditions, params, and extra JOIN for period queries."""
        conditions = [
            "af.context_key = :context_key",
            "af.type = 'solution'",
            # Exclude Haiku jokes from training period stats
            """NOT EXISTS (
                SELECT 1 FROM agent_jokester_model_usage u
                WHERE u.fact_id = af.id AND u.model_name LIKE '%haiku%'
            )""",
        ]
        params: dict[str, Any] = {"context_key": context_key}
        extra_join = ""

        if start is not None:
            conditions.append("af.created_at >= :start")
            params["start"] = start
        if end is not None:
            conditions.append("af.created_at < :end")
            params["end"] = end
        if max_chars is not None:
            extra_join = "JOIN atomic_solution_details asd ON asd.fact_id = af.id"
            conditions.append(f"length(asd.answer_text) < {max_chars}")

        return " AND ".join(conditions), params, extra_join

    def _get_star_distribution(
        self, conn: Any, where: str, params: dict[str, Any], extra_join: str = ""
    ) -> dict[int, int]:
        """Get distribution of star ratings (1-5)."""
        sql = text(f"""
            SELECT (afd.context->>'stars')::int as stars, COUNT(*) as cnt
            FROM atomic_facts af
            JOIN atomic_feedback_details afd ON af.id = afd.fact_id
            {extra_join}
            WHERE {where}
            GROUP BY (afd.context->>'stars')::int
        """)
        rows = conn.execute(sql, params).fetchall()
        return {r[0]: r[1] for r in rows}
